import os
from sqlalchemy import create_engine, inspect, text
from dotenv import load_dotenv
from pathlib import Path

def export_database():
    # Load environment variables
    BASE_DIR = Path(__file__).resolve().parent.parent
    load_dotenv(BASE_DIR / ".env")
    
    db_url = os.getenv("DATABASE_URL", "postgresql+psycopg://usain:usain@localhost:5432/faceattend")
    # Change driver if needed for sqlalchemy
    if db_url.startswith("postgresql+psycopg://"):
        # Ensure it works with psycopg2 or psycopg
        pass

    engine = create_engine(db_url)
    inspector = inspect(engine)
    
    output_file = BASE_DIR / "faceattend_full_export.sql"
    
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("-- Database Export\n")
        f.write("-- Generated by Python script\n\n")
        
        tables = inspector.get_table_names()
        
        with engine.connect() as conn:
            for table_name in tables:
                f.write(f"-- Table: {table_name}\n")
                
                # Get columns for CREATE TABLE (simplified)
                columns = inspector.get_columns(table_name)
                col_defs = []
                for col in columns:
                    col_def = f"{col['name']} {col['type']}"
                    if not col['nullable']:
                        col_def += " NOT NULL"
                    if col.get('default'):
                        col_def += f" DEFAULT {col['default']}"
                    col_defs.append(col_def)
                
                f.write(f"CREATE TABLE IF NOT EXISTS {table_name} (\n")
                f.write("    " + ",\n    ".join(col_defs))
                f.write("\n);\n\n")
                
                # Get data
                result = conn.execute(text(f"SELECT * FROM {table_name}"))
                rows = result.fetchall()
                
                if rows:
                    col_names = [col['name'] for col in columns]
                    for row in rows:
                        vals = []
                        for v in row:
                            if v is None:
                                vals.append("NULL")
                            elif isinstance(v, (int, float)):
                                vals.append(str(v))
                            elif isinstance(v, bool):
                                vals.append("TRUE" if v else "FALSE")
                            else:
                                # Escape single quotes
                                escaped = str(v).replace("'", "''")
                                vals.append(f"'{escaped}'")
                        
                        f.write(f"INSERT INTO {table_name} ({', '.join(col_names)}) VALUES ({', '.join(vals)});\n")
                    f.write("\n")
                
                f.write("-- --------------------------------------------------------\n\n")

    print(f"Export completed: {output_file}")

if __name__ == "__main__":
    export_database()
